use_frameworks!

target 'DKActivityButton_Example' do
  pod 'DKActivityButton', :path => '../'

  target 'DKActivityButton_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
